
project_id = "vhofgqmmovjtcnakowlv"

[functions]
[functions.get-stripe-key]
verify_jwt = false

[functions.stripe-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-stripe-session]
verify_jwt = false

[functions.update-google-doc]
verify_jwt = true

[functions.process-resume]
verify_jwt = true

[functions.auto-save]
verify_jwt = true

[functions.resume-ai-assistant]
verify_jwt = true

[functions.notion-sync]
verify_jwt = false
